beb-manager/web_app/beb_manager/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views

app_name = "beb_manager"

concrete_card_patterns = [
    url(r'^edit/$', views.edit_card, name='edit_card'),
    url(r'^show/$', views.show_card, name='show_card'),
]

concrete_lists_patterns = [
    url(r'^edit/$', views.edit_list, name='edit_list'),
    url(r'^delete/$', views.delete_list, name='delete_list'),
    url(r'^add/$', views.add_card, name='add_card'),
]

tags_patterns = [
    url(r'^add/$', views.add_tag, name='add_tag'),
    url(r'^(?P<tag_id>[0-9]+)/edit/$', views.edit_tag, name='edit_tag'),
    url(r'^(?P<tag_id>[0-9]+)/show/$', views.show_tag, name='show_tag'),
]

concrete_board_patterns = [
    url(r'^$', views.lists, name='lists'),
    url(r'^edit/$', views.edit_board, name='edit_board'),
    url(r'^delete/$', views.delete_board, name='delete_board'),
    url(r'^add/$', views.add_list, name='add_list'),
    url(r'^list/(?P<list_id>[0-9]+)/', include(concrete_lists_patterns)),
    url(r'^tags/', include(tags_patterns)),
    url(r'^card/(?P<card_id>[0-9]+)/', include(concrete_card_patterns)),
    url(r'^assigned/$', views.assigned, name='assigned'),
    url(r'^owned/$', views.owned, name='owned'),
]

board_patterns = [
    url(r'^$', views.boards, name='boards'),
    url(r'^(?P<board_id>[0-9]+)/', include(concrete_board_patterns)),
    url(r'^add/$', views.add_board, name='add_board'),
]

registration_patterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'beb_manager:login'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='home'),
]

urlpatterns = [
    url(r'^', include(board_patterns)),
    url(r'^accounts/', include(registration_patterns)),
]

beb-manager/web_app/web_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('beb_manager.urls')),
]

beb-manager/web_app/beb_manager/models.py
from django.db import models

# Create your models here.

beb-manager/web_app/beb_manager/forms.py
import datetime

from beb_lib.domain_entities.supporting import Priority
import beb_lib.model.exceptions as beb_exceptions
from beb_lib.model.model import Model
from colorful.forms import RGBColorField
from colorful.widgets import ColorFieldWidget
from django import forms
from django.contrib.auth.models import User
from tempus_dominus.widgets import DateTimePicker

from web_app import settings

MODEL = Model(settings.BEB_LIB_DATABASE_PATH)


class SingleInputForm(forms.Form):
    name = forms.CharField(max_length=100)
    can_read = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(), required=False)
    can_write = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(), required=False)


class CardForm(forms.Form):
    def __init__(self, user_id, board_id, *args, **kwargs):
        super(CardForm, self).__init__(*args, **kwargs)
        try:
            tags = MODEL.tag_read()
        except beb_exceptions.TagDoesNotExistError:
            tags = []
        tags_tuple = [(tag.unique_id, tag.name) for tag in tags]
        tags_tuple.insert(0, ('', 'n.s.'))

        try:
            cards = MODEL.get_cards_in_board(board_id, user_id)
        except beb_exceptions.CardDoesNotExistError:
            cards = []
        
        card_lists = MODEL.list_read(board_id, request_user_id=user_id)

        cards_tuple = [(card.unique_id, card.name) for card in cards]
        cards_tuple.insert(0, ('', 'n.s.'))

        lists_tuple = [(card_list.unique_id, card_list.name) for card_list in card_lists]

        self.fields['tags'] = forms.MultipleChoiceField(choices=tags_tuple, required=False)
        self.fields['card_list'] = forms.ChoiceField(choices=lists_tuple, required=False)
        self.fields['children_cards'] = forms.MultipleChoiceField(choices=cards_tuple, required=False)

    name = forms.CharField(required=False, max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Card title'}))
    description = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Card description'}))
    tags = forms.MultipleChoiceField()
    card_list = forms.ChoiceField()
    priority = forms.ChoiceField(choices=[(p.value, Priority(p).name) for p in Priority], required=False)
    expiration_date = forms.DateTimeField(widget=DateTimePicker(options={'minDate': (datetime.date.today() +
                                                                                     datetime.timedelta(
                                                                                         days=1)).strftime('%Y-%m-%d'),
                                                                         'useCurrent': False, }),
                                          required=False)
    children_cards = forms.MultipleChoiceField()
    assignee = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    can_read = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)
    can_write = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)

    interval = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': '5 minutes'}), required=False)
    start_repeat_at = forms.DateTimeField(
        widget=DateTimePicker(options={'minDate': (datetime.date.today()).strftime('%Y-%m-%d'),
                                       'useCurrent': True,
                                       }
                              ),
        required=False
    )


class CardFormWithoutLists(CardForm):
    def __init__(self, *args, **kwargs):
        super(CardFormWithoutLists, self).__init__(*args, **kwargs)
        self.fields.pop('card_list')


class TagForm(forms.Form):
    name = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': 'Tag title'}), required=True)
    color = RGBColorField(widget=ColorFieldWidget(colors=['#61BD4F', '#F2D900', '#FFA111', '#EB5942',
                                                          '#C470DF', '#0576BF', '#00C1E1', '#4FEB9A',
                                                          '#FF72CA', '#355163', '#B3BEC4']))

beb-manager/web_app/beb_manager/views.py
import datetime

import beb_lib.model.exceptions as beb_exceptions
import dateparser
import pytimeparse
from beb_lib.domain_entities.board import Board
from beb_lib.domain_entities.card import Card
from beb_lib.domain_entities.card_list import CardsList
from beb_lib.domain_entities.supporting import Priority, AccessType
from beb_lib.model.model import Model
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from beb_manager.forms import SingleInputForm, CardFormWithoutLists, CardForm, TagForm

MODEL = Model(settings.BEB_LIB_DATABASE_PATH)


def process_plans(func):
    def wrap(request, *args, **kwargs):
        MODEL.trigger_card_plan_creation()
        return func(request, *args, **kwargs)

    return wrap


@process_plans
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('beb_manager:boards')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


@process_plans
@login_required
def boards(request):
    try:
        beb_boards = MODEL.board_read(request_user_id=request.user.id)
        Board.editable = True
        for board in beb_boards:
            board. editable = bool(MODEL.get_right(board.unique_id, Board, request.user.id) & AccessType.WRITE)
    except beb_exceptions.Error:
        beb_boards = []

    return render(request, 'beb_manager/boards/boards.html', {'user_boards': beb_boards, 'container_editable': True})


@process_plans
@login_required
def add_board(request):
    try:
        if request.method == 'POST':
            form = SingleInputForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                try:
                    MODEL.board_write(board_name=name,
                                      request_user_id=request.user.id)
                except beb_exceptions.Error:
                    pass
                return redirect('beb_manager:boards')
        else:
            form = SingleInputForm()
        return render(request, 'beb_manager/boards/add.html', {'form': form, 'container_editable': True})
    except beb_exceptions.AccessDeniedError:
        return HttpResponse('<h1>Access Denied</h1>')
    except beb_exceptions.Error:
        return redirect('beb_manager:boards')


@process_plans
@login_required
def edit_board(request, board_id):
    try:
        board = MODEL.board_read(board_id, request_user_id=request.user.id)[0]

        if request.method == 'POST':
            form = SingleInputForm(request.POST)
            if form.is_valid():
                if 'save' in request.POST:
                    new_name = form.cleaned_data['name']

                    can_read = form.cleaned_data['can_read']
                    can_write = form.cleaned_data['can_write']

                    MODEL.board_write(board.unique_id, new_name, request_user_id=request.user.id)

                    if can_read:
                        for user in can_read:
                            MODEL.add_right(board_id, Board, user.id, AccessType.READ)
                    if can_write:
                        for user in can_write:
                            MODEL.add_right(board_id, Board, user.id, AccessType.WRITE)

                    for user in User.objects.all():
                        if user not in can_read and can_read:
                            MODEL.remove_right(board_id, Board, user.id, AccessType.READ)
                        if user not in can_write and can_write:
                            MODEL.remove_right(board_id, Board, user.id, AccessType.WRITE)
                elif 'delete' in request.POST:
                    MODEL.board_delete(board_id, request_user_id=request.user.id)
                return redirect('beb_manager:boards')
        else:
            can_write = []
            can_read = []

            for user in User.objects.all():
                if bool(MODEL.get_right(board_id, Board, user.id) & AccessType.READ):
                    can_read.append(user)
                if bool(MODEL.get_right(board_id, Board, user.id) & AccessType.WRITE):
                    can_write.append(user)

            form = SingleInputForm(initial={'name': board.name, 'can_read': can_read, 'can_write': can_write})
        editable = bool(MODEL.get_right(board_id, Board, request.user.id) & AccessType.WRITE)
        return render(request, 'beb_manager/boards/edit.html', {'form': form, 'container_editable': editable})
    except beb_exceptions.AccessDeniedError:
        return HttpResponse('<h1>Access Denied</h1>')
    except beb_exceptions.Error:
        return redirect('beb_manager:boards')


@process_plans
@login_required
def delete_board(request, board_id):
    try:
        if request.method == 'POST':
            MODEL.board_delete(board_id, request_user_id=request.user.id)
        return redirect('beb_manager:boards')
    except beb_exceptions.AccessDeniedError:
        return HttpResponse('<h1>Access Denied</h1>')


@process_plans
@login_required
def lists(request, board_id):
    try:
        tags = MODEL.tag_read()
        for i in range(len(tags)):
            tags[i].color = '#{0:06X}'.format(tags[i].color)
    except beb_exceptions.TagDoesNotExistError:
        tags = []
    editable = bool(MODEL.get_right(board_id, Board, request.user.id) & AccessType.WRITE)
    try:
        today = datetime.datetime.today()
        lists_models = MODEL.list_read(board_id, request_user_id=request.user.id)
        beb_lists = []
        Card.editable = True
        CardsList.editable = True

        for card_list in lists_models:
            card_list.editable = bool(MODEL.get_right(card_list.unique_id, CardsList, request.user.id)
                                      & AccessType.WRITE)
            try:
                cards = MODEL.card_read(card_list.unique_id, request_user_id=request.user.id)
                for card in cards:
                    card.editable = bool(MODEL.get_right(card.unique_id, Card, request.user.id) & AccessType.WRITE)
                    for i in range(len(card.tags)):
                        card.tags[i] = MODEL.tag_read(tag_id=card.tags[i])[0]
                        card.tags[i].color = '#{0:06X}'.format(card.tags[i].color)
            except beb_exceptions.CardDoesNotExistError:
                cards = []

            card_list._cards = cards
            beb_lists.append(card_list)

        return render(request, 'beb_manager/lists/lists.html',
                      {'beb_lists': beb_lists, 'board_id': board_id, 'tags': tags,
                       'today': today, 'container_editable': editable})

    except beb_exceptions.ListDoesNotExistError:
        return render(request, 'beb_manager/lists/lists.html',
                      {'beb_lists': [], 'board_id': board_id, 'tags': tags,
                       'today': today, 'container_editable': editable})
    except beb_exceptions.AccessDeniedError:
        return HttpResponse('<h1>Access Denied</h1>')
    except beb_exceptions.Error:
        return redirect('beb_manager:boards')


@process_plans
@login_required
def add_list(request, board_id):
    try:
        if request.method == 'POST':
            form = SingleInputForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                MODEL.list_write(board_id, list_name=name,
                                 request_user_id=request.user.id)
        else:
            form = SingleInputForm()

        editable = bool(MODEL.get_right(board_id, Board, request.user.id) & AccessType.WRITE)
        return render(request, 'beb_manager/lists/add.html', {'form': form, 'container_editable': editable})
    except beb_exceptions.AccessDeniedError:
        return HttpResponse('<h1>Access Denied</h1>')


@process_plans
@login_required
def delete_list(request, board_id, list_id):
    if request.method == 'POST':
        MODEL.list_delete(list_id, request_user_id=request.user.id)
    return redirect('beb_manager:lists', board_id)


@process_plans
@login_required
def edit_list(request, board_id, list_id):
    try:
        card_list = MODEL.list_read(None, list_id, request_user_id=request.user.id)[0]

        if request.method == 'POST':
            form = SingleInputForm(request.POST)
            if form.is_valid():
                if 'save' in request.POST:
                    new_name = form.cleaned_data['name']

                    can_read = form.cleaned_data['can_read']
                    can_write = form.cleaned_data['can_write']
                    MODEL.list_write(board_id, list_id, new_name, request.user.id)

                    if can_read:
                        for user in can_read:
                            MODEL.add_right(list_id, CardsList, user.id, AccessType.READ)
                    if can_write:
                        for user in can_write:
                            MODEL.add_right(list_id, CardsList, user.id, AccessType.WRITE)

                    for user in User.objects.all():
                        if user not in can_read and can_read:
                            MODEL.remove_right(list_id, CardsList, user.id, AccessType.READ)
                        if user not in can_write and can_write:
                            MODEL.remove_right(list_id, CardsList, user.id, AccessType.WRITE)
                elif 'delete' in request.POST:

beb-manager/web_app/beb_manager/templates/beb_manager/cards/add.html
{% extends 'base.html' %}

{% block title %}New task{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    {{ form.media }}
    <h2>New card</h2>
    <div class='form' style="position: relative">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-success">Submit</button>
                <input class='btn btn-secondary' type=button value="Back" onClick="history.go(-1);">
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

beb-manager/web_app/beb_manager/templates/beb_manager/cards/edit.html
{% extends 'base.html' %}

{% block title %}Edit task{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    {{ form.media }}
    <h2>Edit card</h2>
    <div class='form' style="position: relative">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-success" name="save">Submit</button>
                <input class='btn btn-secondary' type=button value="Back" onClick="history.go(-1);">
                <button type="submit"
                        class="btn btn-danger float-right"
                        name="delete"
                        onclick="return confirm('Are you sure you want to delete this task?');">
                    Delete
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

beb-manager/web_app/beb_manager/templates/beb_manager/cards/show.html
{% extends 'base.html' %}

{% block title %}Card info{% endblock %}
{% block content %}
    <h2>Card info</h2>
    <table class="table table-striped">
        <tbody>
        <tr>
            <td class="title">ID</td>
            <td>{{ card.unique_id }}</td>
        </tr>
        <tr>
            <td class="title">Title</td>
            <td>{{ card.name }}</td>
        </tr>
        {% if card.description %}
            <tr>
                <td class="title">Description</td>
                <td>{{ card.description }}</td>
            </tr>
        {% endif %}
        {% if card.tags %}
            <tr>
                <td class="title">Tags</td>
                <td>
                    {% for tag in card.tags %}
                        <h5 style="display: inline-block">
                            <a href="{% url 'beb_manager:show_tag' board_id tag.unique_id %}"
                               class="badge badge-primary"
                               style="background-color: {{ tag.color }}">
                                {{ tag.name }}
                            </a>
                        </h5>
                    {% endfor %}
                </td>
            </tr>
        {% endif %}
        <tr>
            <td class="title">Priority</td>
            <td>
                <h5>{{ card.priority }}</h5>
            </td>
        </tr>
        <tr>
            <td class="title">List</td>
            <td>
                ID: {{ card_list.unique_id }}, Name: {{ card_list.name }}
            </td>
        </tr>
        <tr>
            <td class="title">Created on</td>
            <td>{{ card.created }}</td>
        </tr>
        <tr>
            <td class="title">Updated on</td>
            <td>{{ card.last_modified }}</td>
        </tr>
        {% if card.expiration_date %}
            <tr>
                <td class="title">Expiration date on</td>
                <td>{{ card.expiration_date }}</td>
            </tr>
        {% endif %}
        {% if card.children %}
            <tr>
                <td class="title">Children cards</td>
                {% for child in card.children %}
                    <td>
                        <a href="{% url 'beb_manager:show_card' board_id child.unique_id %}">{{ child.name }}</a>
                    </td>
                {% endfor %}
            </tr>
        {% endif %}
        {% if card.assignee_id %}
            <tr>
                <td class="title">Assigned user</td>
                <td>{{ card.assignee_id.username }}</td>
            </tr>
        {% endif %}
        <tr>
            <td class="title">Creator</td>
            <td>{{ card.user_id.username }}</td>
        </tr>
        {% if plan %}
            <tr>
                <td class="title">Interval</td>
                <td>{{ plan.interval }}</td>
            </tr>
            <tr>
                <td class="title">Last created on</td>
                <td>{{ plan.last_created_at }}</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
    <input class='btn btn-secondary float-right' type=button value="Back" onClick="javascript:history.go(-1);">
    <a {% if card.editable %}
        href="{% url 'beb_manager:edit_card' board_id card.unique_id %}"
    {% endif %}
        class='btn btn-primary'>Edit</a>
{% endblock %}

beb-manager/web_app/beb_manager/templates/beb_manager/cards/sorted.html
{% extends 'base.html' %}
{% load fontawesome %}


{% block title %}Sorted cards{% endblock %}
{% block plus_url %}{% url 'beb_manager:add_board' %}{% endblock %}

{% block content %}
    <h2>
        {{ header_title }}
        <input class='btn btn-secondary float-right' style="margin-top: 3pt" type=button value="Back"
               onClick="history.go(-1);">
    </h2>
    <div class="card-columns">
        {% for card in cards %}
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'beb_manager:show_card' board_id card.unique_id %}">
                        <h5 class="card-title">{{ card.name }}</h5>
                    </a>
                    <p class="card-text">{{ card.description }}</p>
                    <p class="card-text">
                        <small class="text-muted">Last modified: {{ card.last_modified }}</small>
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}